name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        ghc: ['8.10.7', '9.2.6', '9.4.8']
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: ghcup
      run: |
        ghcup install ghc ${{ matrix.ghc }}
        ghcup set ghc ${{ matrix.ghc }}
        ghcup install cabal latest
        ghcup set cabal latest

    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all
